# Generated by Django 5.2.3 on 2025-06-25 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicador',
            name='descricao',
        ),
        migrations.AddField(
            model_name='indicador',
            name='tipo_meta',
            field=models.CharField(choices=[('crescente', 'Para cima'), ('decrescente', 'Para baixo'), ('acompanhamento', 'Acompanhamento')], default='crescente', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indicador',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='api.setor'),
        ),
    ]
