# Generated by Django 5.2.3 on 2025-06-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='setor',
        ),
        migrations.AddField(
            model_name='usuario',
            name='setores',
            field=models.ManyToManyField(blank=True, to='api.setor'),
        ),
    ]
