# Generated by Django 5.2.3 on 2025-06-23 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_usuario_setor_usuario_setores'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissaoIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.indicador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
