# Generated by Django 5.2.3 on 2025-07-09 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_preenchimento_origem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notificacao',
        ),
    ]
