# Generated by Django 5.2.3 on 2025-07-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_configuracaoarmazenamento_dia_limite_preenchimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='analise_meta',
            field=models.CharField(choices=[('crescente', 'Para cima'), ('decrescente', 'Para baixo'), ('acompanhamento', 'Monitoramento')], default='crescente', max_length=20),
        ),
        migrations.AddField(
            model_name='indicador',
            name='extracao_indicador',
            field=models.TextField(blank=True, help_text='Instruções de como extrair esse indicador'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='mes_inicial',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicador',
            name='periodicidade',
            field=models.PositiveIntegerField(default=1, help_text='Periodicidade em meses (1 a 12)'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='visibilidade',
            field=models.BooleanField(default=True, help_text='Se o indicador será visível para todos'),
        ),
    ]
