# Generated by Django 5.2.3 on 2025-07-09 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_indicador_analise_meta_indicador_extracao_indicador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicador',
            name='analise_meta',
        ),
    ]
