# Generated by Django 5.2.3 on 2025-07-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_indicador_analise_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_limite_preenchimento', models.PositiveIntegerField(default=10)),
            ],
        ),
    ]
