# Generated by Django 5.2.3 on 2025-07-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_configuracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicador',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='indicador',
            name='tipo_meta',
            field=models.CharField(choices=[('crescente', 'Para cima'), ('decrescente', 'Para baixo'), ('monitoramento', 'Monitoramento')], max_length=20),
        ),
    ]
