# Generated by Django 5.2.3 on 2025-07-10 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_indicador_descricao_alter_indicador_tipo_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(help_text='Representa o mês da meta. Use sempre o primeiro dia do mês.')),
                ('valor_meta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_mensais', to='api.indicador')),
            ],
            options={
                'ordering': ['mes'],
                'unique_together': {('indicador', 'mes')},
            },
        ),
    ]
