# Generated by Django 5.2.3 on 2025-07-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_metamensal'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='tipo_valor',
            field=models.CharField(choices=[('numeral', 'Numeral'), ('monetario', 'Monetário'), ('percentual', 'Percentual')], default='numeral', max_length=20),
        ),
    ]
