# Generated by Django 5.2.3 on 2025-07-18 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_indicador_tipo_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('username', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('default_from_email', models.EmailField(max_length=254)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.configuracao')),
            ],
        ),
    ]
