# Generated by Django 5.2.3 on 2025-08-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_setor_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Se o indicador está ativo ou inativo'),
        ),
    ]
